### ISSUE TITLE
[bug] convtools_invitations ERROR in /bot rsvp for some users

### ISSUE THREAD

**Issue by FrNico** [nylonee/hangupsbot#166]
Context:
 - creating invites with /bot invite to xxxxxx users from yyyyyyyy
 - bot is creating invites for all users
 - some users can use /bot rsvp fine, some others can't
 - if I look into memory.json for invite codes, it's there for these users
 - if they use /bot rsvp `<code>` it's working

```
Error seen in logs when users are doing /bot rsvp (and failing):
2015-05-01 03:05:33,293 - root - ERROR - CommandDispatcher.run: rsvp
Traceback (most recent call last):
  File "/opt/hangupsbot/hangupsbot/commands.py", line 42, in run
    yield from func(bot, event, *args, **kwds)
  File "/opt/hangupsbot/hangupsbot/plugins/convtools_invitations.py", line 214, in rsvp
    conversation_name = get_conv_name(bot._conv_list.get(invite["group_id"]))
  File "/usr/local/lib/python3.4/dist-packages/hangups-0.2.6-py3.4.egg/hangups/conversation.py", line 367, in get
    return self._conv_dict[conv_id]
KeyError: '<XXXXXXXXXXXXXXXXXXXXX>'
```

**Comment by endofline** [comment]
could be instance of the bot forgetting older conversations - considering a workaround of using invite labels to replace the usage conversation names since the hangups conversation list seems to be unreliable when the bot has a lot of active conversations
