### ISSUE TITLE
If port 8080 is busy what we need to choose?

### ISSUE THREAD

**Issue by sasha2002** [nylonee/hangupsbot#86]
When bot start(in config i have 8080) i can't receive any PM, if i try to edit it to different port like 8081 i got this ::
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /receive/UgyMnN07kw8Yupcnavd4AaABAQ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)
2015-02-12 14:13:15,076 - root - INFO - memory: UgxNZ6rK7YFz0wip7G54AaABAQ is 1on1 with 100879078835333107083
2015-02-12 14:13:16,676 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 127.0.0.1
2015-02-12 14:13:16,677 - root - ERROR - ('_execute_hooks()', <class 'hooks.hubotsend.post.sender'>, ConnectionError(MaxRetryError("HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /receive/UgyMnN07kw8Yupcnavd4AaABAQ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)",),))
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 493, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 291, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/packages/urllib3/connection.py", line 106, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/packages/urllib3/connection.py", line 90, in _new_conn
    (self.host, self.port), self.timeout, *extra_args)
  File "/usr/local/lib/python3.4/socket.py", line 509, in create_connection
    raise err
  File "/usr/local/lib/python3.4/socket.py", line 500, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/adapters.py", line 327, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/packages/urllib3/connectionpool.py", line 543, in urlopen
    raise MaxRetryError(self, url, e)
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /receive/UgyMnN07kw8Yupcnavd4AaABAQ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hangupsbot.py", line 506, in _execute_hook
    method(parameters)
  File "/home/hangupsbot/hangupsbot/hooks/hubotsend/post.py", line 37, in on_chat_message
    r = requests.post(url, data = json.dumps(payload), headers = headers, verify=False)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/requests-2.3.0-py3.4.egg/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8081): Max retries exceeded with url: /receive/UgyMnN07kw8Yupcnavd4AaABAQ (Caused by <class 'ConnectionRefusedError'>: [Errno 111] Connection refused)

Can someone suggest me how to fix this?

**Comment by endofline** [comment]
Is your Hangupsbot integrated with Hubot? It seems that you are running the Hubot hook.

If you aren't, disable the hook from your `config.json` by finding the following lines and remove them entirely:
```
    {
      "config": {
        "HUBOT_URL": "http://127.0.0.1:8080/receive/"
      },
      "module": "hooks.hubotsend.post.sender"
    }
```

**Comment by sasha2002** [comment]
thanks for hint!
Now PM's work well

**Comment by endofline** [comment]
No problem :) Will fix the default config.json for future problems as well
