### ISSUE TITLE
mention plugin problem

### ISSUE THREAD

**Issue by sasha2002** [nylonee/hangupsbot#87]
2015-02-12 15:51:07,633 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 127.0.0.1
2015-02-12 15:51:07,850 - requests.packages.urllib3.connectionpool - DEBUG - "POST /receive/UgzNRcid-454545-BXrp4AaABAQ HTTP/1.1" 404 357
2015-02-12 15:51:07,853 - root - INFO - list_conversations() returned 4 conversation(s)
2015-02-12 15:51:07,854 - root - INFO - @mention 'WORD' in 'Some chat ' (UgzNRcid-454545-BXrp4AaABAQ)

When i try to test what's wrong ::
/bot mention WORD test
@mentions:
Nobody was successfully @mentioned ;-(

**Comment by endofline** [comment]
Do you have anybody in the same chat with the name (or part of the name) "word"? If there isn't, nothing is going to happen and you will get the output as above. This is not an error. Try /bot mention (part of your name) test

Also, please see the rest of the README for instructions on how to use mentions: https://github.com/nylonee/hangupsbot/blob/master/README.md

**Comment by sasha2002** [comment]
To be clear ::
1. I add bot to some chat with 20+ users
2. I do :: /bot mention TEXT
3. some user mention me with @WORD 
4. i got this error in log, and no mention in 1and1 chat(i mean chat with bot)
5. try to do this /bot mention WORD test , nothing happened

What i observe, that bot can't POST to chat with me, and he try to post to unknown ID. my chat ID is different

**Comment by endofline** [comment]
When you send /bot help do you get any response on your 1to1 channel with the bot?

**Comment by endofline** [comment]
Back to a computer now, was on mobile earlier:

Firstly, these log lines have nothing to do with mentions:
```
2015-02-12 15:51:07,633 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): 127.0.0.1
2015-02-12 15:51:07,850 - requests.packages.urllib3.connectionpool - DEBUG - "POST /receive/UgzNRcid-454545-BXrp4AaABAQ HTTP/1.1" 404 357
```

The conversation id you see in this log line should match the `/bot whereami` output inside the hangout where @WORD was mentioned (so it won't be your 1on1 id):
```
2015-02-12 15:51:07,854 - root - INFO - @mention 'WORD' in 'Some chat ' (UgzNRcid-454545-BXrp4AaABAQ)
```

Have you re-opening your 1on1 with the bot and saying hi again and then re-doing the `/bot mention WORD test` in another group hangout? It seems like the bot can't find your 1on1 at all - as there should be more INFO logs after the last log line.

**Comment by sasha2002** [comment]
Yes "/bot help" in any chat, open a 1on1 chat and reply.
i will test it tomorrow and will reply here

**Comment by nylonee** [comment]
@sasha2002 feel free to hit me up on [hangouts](plus.google.com/+NihalMirpuri) if you need help with these errors. I'm more than happy to help, I'd like to keep this issue tracker for bugs rather than general Q&A and help.

**Comment by nylonee** [comment]
Just had a chat with @sasha2002 about this. It looks like the bug is most likely related to the fact that a dnd had never been used on the bot, and thus when [L189](https://github.com/nylonee/hangupsbot/blob/master/hangupsbot/plugins/mentions.py#L189) of the mentions plugin is called, an UnboundLocalError is referenced.

Full traceback (with private information replaced with xxxxxxx):
```
2015-02-12 17:43:13,452 - root - INFO - @mention 'nihal' in 'xxxxxxxxxxxxxxxxx' (xxxxxxxxxxxxxxxxxxxxxxxxxx)
2015-02-12 17:43:13,452 - root - INFO - user Nihal Mirpuri (109883513693796164843) is present
2015-02-12 17:43:13,452 - root - ERROR - CommandDispatcher.run: mention
Traceback (most recent call last):
 File "/home/hangupsbot/hangupsbot/commands.py", line 34, in run
   yield from func(bot, event, *args, **kwds)
 File "/usr/local/lib/python3.4/asyncio/coroutines.py", line 141, in coro
   res = func(*args, **kw)
 File "/home/hangupsbot/hangupsbot/plugins/mentions.py", line 189, in mention
   if donotdisturb:
UnboundLocalError: local variable 'donotdisturb' referenced before assignment
```

I will work on pushing a bugfix to this shortly. For now toggling DND on and off once should fix the problem.

**Comment by endofline** [comment]
This is already fixed in the PR that was merged into staging.

**Comment by nylonee** [comment]
My apologies, yes it looks like #80 resolves this issue. Will do some more testing then push this bugfix to master. Thanks
